namespace INK.ERP.Application.Features.MasterData.Employees.DTOs;

public record EmployeeDto(
    Guid Id,
    Guid CompanyId,
    string? CompanyName,
    Guid BranchId,
    string? BranchName,
    Guid DepartmentId,
    string? DepartmentName,
    Guid? WarehouseId,
    string? WarehouseName,
    string? WarehouseCode,
    Guid DesignationId,
    string? DesignationTitle,
    Guid? EmployeeRoleId,
    string? EmployeeRoleName,
    string EmployeeCode,
    string FirstName,
    string LastName,
    string FullName,
    string Email,
    string Phone,
    DateTime JoiningDate,
    decimal? Salary,
    bool IsActive,
    DateTime CreatedAtUtc);
